development: &default
  adapter: postgresql
  database: umago_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: umago_test

production:
  <<: *default
  database: umago_production
  username: umago
  password: <%= ENV['UMAGO_DATABASE_PASSWORD'] %>
